#!/bin/sh
set -eu

OFFSET=${PORT_OFFSET:-0}

HARDHAT_BASE=8545
FACILITATOR_BASE=8080
SEQUENCER_BASE=4001
SERVICE_BASE=4000
POSTGRES_BASE=5432

HARDHAT_PORT=$((HARDHAT_BASE + OFFSET))
FACILITATOR_PORT=$((FACILITATOR_BASE + OFFSET))
SEQUENCER_PORT=$((SEQUENCER_BASE + OFFSET))
SERVICE_PORT=$((SERVICE_BASE + OFFSET))
POSTGRES_PORT=$((POSTGRES_BASE + OFFSET))

cat > .env <<EOT
PORT_OFFSET=${OFFSET}
HARDHAT_PORT=${HARDHAT_PORT}
FACILITATOR_PORT=${FACILITATOR_PORT}
SEQUENCER_PORT=${SEQUENCER_PORT}
SERVICE_PORT=${SERVICE_PORT}
POSTGRES_PORT=${POSTGRES_PORT}
EOT

echo "Wrote .env with offset ${OFFSET}".
